project:
  type: website
  output-dir: docs
  
website: 
  title: "Viet Nguyen"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    toc: true
      
editor: visual